services:
  db:
    image: bitespeed-db-image
    restart: always
    container_name: contact-db-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: bitespeed-app-image
    container_name: contact-app-container
    environment:
      - TZ=UTC
      - POSTGRES_HOST=db
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"

volumes:
  postgres_data:
