services:
  db:
    image: db-image
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresDB_data:/var/lib/postgresql/data
  app:
    image: app-image
    container_name: event-app-container
    environment:
      - TZ=UTC
      - POSTGRES_HOST=db
      - PORT=3000
    env_file:
      - ./.env
    ports:
      - "${PORT}:3000"
volumes:
  postgresDB_data: